<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableSdkContainerDebugging>True</EnableSdkContainerDebugging>
    <ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:10.0</ContainerBaseImage>
    <UserSecretsId>0f8e28ff-2be2-406f-aeb4-6c4cca43cd07</UserSecretsId>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <ContainerPort Include="8081" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapr.AspNetCore" Version="1.17.6" />
    <PackageReference Include="Dapr.Client" Version="1.17.6" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\dapr-lab.ServiceDefaults\dapr-lab.ServiceDefaults.csproj" />
    <ProjectReference Include="..\DaprEventStore\DaprEventStore.csproj" />
  </ItemGroup>

</Project>
